"""add missing columns from models

Revision ID: 95ab0660938e
Revises: d4e5f6a7b8c9
Create Date: 2026-06-30 16:20:06.614588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ab0660938e'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulado_questao_id'), table_name='simulado_questao')
    op.drop_index(op.f('ix_simulado_questao_num_ordem'), table_name='simulado_questao')
    op.drop_index(op.f('ix_simulado_questao_simulacro_numero'), table_name='simulado_questao')
    op.drop_table('simulado_questao')
    op.drop_table('audit_logs')
    connection = op.get_bind()
    
    # Comprobar si existe la tabla _backup_desafios_f3
    result_f3 = connection.execute(sa.text("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = '_backup_desafios_f3');")).scalar()
    if result_f3:
        op.drop_table('_backup_desafios_f3')
        
    # Comprobar si existe la tabla _backup_desafios_f4_f5
    result_f4_f5 = connection.execute(sa.text("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = '_backup_desafios_f4_f5');")).scalar()
    if result_f4_f5:
        op.drop_table('_backup_desafios_f4_f5')
    op.drop_index(op.f('ix_simulado_sessions_alumno_id'), table_name='simulado_sessions')
    op.drop_index(op.f('ix_simulado_sessions_estado'), table_name='simulado_sessions')
    op.drop_index(op.f('ix_simulado_sessions_fase_id'), table_name='simulado_sessions')
    op.drop_index(op.f('ix_simulado_sessions_id'), table_name='simulado_sessions')
    op.drop_index(op.f('ix_simulado_sessions_simulacro_numero'), table_name='simulado_sessions')
    op.drop_table('simulado_sessions')
    op.drop_constraint(op.f('alumnos_user_id_fkey'), 'alumnos', type_='foreignkey')
    op.create_foreign_key(None, 'alumnos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('niveles_teoria_pool', sa.Column('revisado_admin', sa.Boolean(), nullable=True))
    op.add_column('niveles_teoria_pool', sa.Column('revisado_por', sa.String(), nullable=True))
    op.add_column('niveles_teoria_pool', sa.Column('fecha_revision', sa.DateTime(), nullable=True))
    op.add_column('preguntas', sa.Column('revisado_admin', sa.Boolean(), nullable=True))
    op.add_column('preguntas', sa.Column('revisado_por', sa.String(), nullable=True))
    op.add_column('preguntas', sa.Column('fecha_revision', sa.DateTime(), nullable=True))
    # op.create_foreign_key(None, 'preguntas', 'users', ['creado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preguntas', type_='foreignkey')
    op.drop_column('preguntas', 'fecha_revision')
    op.drop_column('preguntas', 'revisado_por')
    op.drop_column('preguntas', 'revisado_admin')
    op.drop_column('niveles_teoria_pool', 'fecha_revision')
    op.drop_column('niveles_teoria_pool', 'revisado_por')
    op.drop_column('niveles_teoria_pool', 'revisado_admin')
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.create_foreign_key(op.f('alumnos_user_id_fkey'), 'alumnos', 'users', ['user_id'], ['id'])
    op.create_table('simulado_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('alumno_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modulo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nivel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('respuestas_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('marcadores_revision', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tiempo_restante_segundos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('simulacro_numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pregunta_ids_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], name=op.f('simulado_sessions_alumno_id_fkey')),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], name=op.f('fk_simulado_sessions_fase_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('simulado_sessions_pkey'))
    )
    op.create_index(op.f('ix_simulado_sessions_simulacro_numero'), 'simulado_sessions', ['simulacro_numero'], unique=False)
    op.create_index(op.f('ix_simulado_sessions_id'), 'simulado_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_simulado_sessions_fase_id'), 'simulado_sessions', ['fase_id'], unique=False)
    op.create_index(op.f('ix_simulado_sessions_estado'), 'simulado_sessions', ['estado'], unique=False)
    op.create_index(op.f('ix_simulado_sessions_alumno_id'), 'simulado_sessions', ['alumno_id'], unique=False)
    op.create_table('_backup_desafios_f4_f5',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seccion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_nivel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operacion', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('tipo_pregunta', sa.VARCHAR(length=21), autoincrement=False, nullable=True),
    sa.Column('enunciado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('respuesta_correcta', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('datos_numericos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('explicacion_paso_a_paso', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requiere_subrayado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('palabras_clave', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('errores_previstos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ultima_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payload_tokenizado', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estructura_padre_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_desafios_f3',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seccion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_nivel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operacion', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('tipo_pregunta', sa.VARCHAR(length=21), autoincrement=False, nullable=True),
    sa.Column('enunciado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('respuesta_correcta', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('datos_numericos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('explicacion_paso_a_paso', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requiere_subrayado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('palabras_clave', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('errores_previstos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ultima_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payload_tokenizado', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estructura_padre_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('simulado_questao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('simulacro_numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ordem_na_prova', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enunciado', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alternativa_a', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alternativa_b', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alternativa_c', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alternativa_d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alternativa_correta', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('resolucao', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tema', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('dificuldade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ano_prova', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('simulado_questao_pkey'))
    )
    op.create_index(op.f('ix_simulado_questao_simulacro_numero'), 'simulado_questao', ['simulacro_numero'], unique=False)
    op.create_index(op.f('ix_simulado_questao_num_ordem'), 'simulado_questao', ['simulacro_numero', 'ordem_na_prova'], unique=False)
    op.create_index(op.f('ix_simulado_questao_id'), 'simulado_questao', ['id'], unique=False)
    # ### end Alembic commands ###
