"""create_ux_feedback_table

Revision ID: ae5a3aaa46e8
Revises: 95ab0660938e
Create Date: 2026-07-07 01:02:48.202329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae5a3aaa46e8'
down_revision: Union[str, Sequence[str], None] = '95ab0660938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ux_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.String(length=100), nullable=True),
    sa.Column('paso_actual', sa.Integer(), nullable=True),
    sa.Column('dom_selector', sa.Text(), nullable=False),
    sa.Column('viewport', sa.String(length=50), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('BUG_VISUAL', 'TEXTO', 'PROPUESTA_UX', 'RENDIMIENTO', name='ux_feedback_tipo', native_enum=False), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('app_state', sa.JSON(), nullable=True),
    sa.Column('screenshot_url', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_DESARROLLO', 'RESUELTO', 'RECHAZADO', name='ux_feedback_estado', native_enum=False), nullable=False),
    sa.Column('desarrollador_notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ux_feedbacks_estado'), 'ux_feedbacks', ['estado'], unique=False)
    op.create_index(op.f('ix_ux_feedbacks_fase'), 'ux_feedbacks', ['fase'], unique=False)
    op.create_index(op.f('ix_ux_feedbacks_id'), 'ux_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_ux_feedbacks_modulo_id'), 'ux_feedbacks', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_ux_feedbacks_nivel_id'), 'ux_feedbacks', ['nivel_id'], unique=False)
    op.create_index(op.f('ix_ux_feedbacks_pregunta_id'), 'ux_feedbacks', ['pregunta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ux_feedbacks_pregunta_id'), table_name='ux_feedbacks')
    op.drop_index(op.f('ix_ux_feedbacks_nivel_id'), table_name='ux_feedbacks')
    op.drop_index(op.f('ix_ux_feedbacks_modulo_id'), table_name='ux_feedbacks')
    op.drop_index(op.f('ix_ux_feedbacks_id'), table_name='ux_feedbacks')
    op.drop_index(op.f('ix_ux_feedbacks_fase'), table_name='ux_feedbacks')
    op.drop_index(op.f('ix_ux_feedbacks_estado'), table_name='ux_feedbacks')
    op.drop_table('ux_feedbacks')
    # ### end Alembic commands ###
