"""
Banco de preguntas de los Simulados (Fase 9 - "Simulados Colegio Pedro II").

Reemplaza el stub anterior (3 preguntas hardcodeadas -- una en portugués e
incontestable -- repetidas al azar 200 veces). Las 20 preguntas están basadas
en el análisis matricial del examen real de admisión al 6º año del Colégio
Militar do Rio de Janeiro (ver `coelgiomilitar.md` en la raíz del repo),
adaptadas al español y a un nivel resoluble con cálculo (opción múltiple).

Cada pregunta lleva su respuesta correcta VERIFICADA, 3 distractores
pedagógicos (varios encarnan las "trampas" descritas en el análisis) y una
explicación breve. El seeder combina correcta + distractores y los baraja de
forma determinista por sección, garantizando 10 preguntas DISTINTAS por
simulacro y variedad entre secciones.
"""

# tema | enunciado | correcta | distractores(3) | explicacion | dificultad(1-3)
BANCO_SIMULADOS = [
    {
        "tema": "Estadística: media aritmética",
        "enunciado": "Un gráfico de barras muestra las temperaturas de 5 días: 18, 20, 22, 19 y 21 °C. ¿Cuál fue la temperatura media?",
        "correcta": "20",
        "distractores": ["19", "21", "22"],
        "explicacion": "Suma los 5 valores (18+20+22+19+21 = 100) y divide entre 5: 100 ÷ 5 = 20 °C.",
        "dificultad": 1,
    },
    {
        "tema": "Sistema métrico decimal",
        "enunciado": "Mariana entrenó corriendo 2 km, después 1500 m y después 30000 cm. ¿Cuántos metros corrió en total?",
        "correcta": "3800",
        "distractores": ["3350", "3500", "33500"],
        "explicacion": "Convierte todo a metros: 2 km = 2000 m, 1500 m = 1500 m, 30000 cm = 300 m. Total: 2000+1500+300 = 3800 m.",
        "dificultad": 2,
    },
    {
        "tema": "Fracciones de una cantidad (dinero)",
        "enunciado": "Tito guardó 360 monedas. 1/3 son de R$1, 1/4 son de R$0,50 y 1/6 son de R$0,25. El resto son de R$0,10. ¿Cuántas monedas de R$0,10 tiene?",
        "correcta": "90",
        "distractores": ["60", "120", "72"],
        "explicacion": "1/3 de 360 = 120; 1/4 = 90; 1/6 = 60. Suman 270. El resto: 360 − 270 = 90 monedas.",
        "dificultad": 2,
    },
    {
        "tema": "Porcentaje del remanente",
        "enunciado": "Ana gastó 3/5 de su dinero en libros y el 20% de lo que le quedó en transporte. Si tenía R$200, ¿cuánto gastó en transporte?",
        "correcta": "R$ 16",
        "distractores": ["R$ 40", "R$ 24", "R$ 80"],
        "explicacion": "En libros gastó 3/5 de 200 = 120, le quedaron 80. El 20% de 80 = 16.",
        "dificultad": 3,
    },
    {
        "tema": "Geometría espacial: cubo pintado",
        "enunciado": "Un cubo de 3×3×3 (27 cubitos) se pinta por fuera y luego se separa en cubitos. ¿Cuántos cubitos tienen exactamente 2 caras pintadas?",
        "correcta": "12",
        "distractores": ["8", "6", "4"],
        "explicacion": "Los cubitos con 2 caras pintadas están en las aristas (sin las esquinas). Un cubo tiene 12 aristas y en cada una hay 1 cubito central: 12.",
        "dificultad": 3,
    },
    {
        "tema": "Números romanos",
        "enunciado": "Un número de cuatro cifras es 2358. ¿Cómo se escribe su mitad en números romanos?",
        "correcta": "MCLXXIX",
        "distractores": ["MCXCIX", "MCLXXVIIII", "MDCLXXIX"],
        "explicacion": "La mitad de 2358 es 1179 = 1000 (M) + 100 (C) + 50 (L) + 20 (XX) + 9 (IX) = MCLXXIX.",
        "dificultad": 3,
    },
    {
        "tema": "Razonamiento espacial: el dado",
        "enunciado": "En un dado común, las caras opuestas suman 7. Si una cara muestra 2 puntos, ¿cuántos puntos tiene la cara opuesta?",
        "correcta": "5",
        "distractores": ["6", "4", "7"],
        "explicacion": "Caras opuestas suman 7, entonces la opuesta al 2 es 7 − 2 = 5.",
        "dificultad": 1,
    },
    {
        "tema": "Números primos",
        "enunciado": "¿Cuántos de estos números son primos: 109, 161, 221, 251, 263?",
        "correcta": "3",
        "distractores": ["2", "4", "5"],
        "explicacion": "Primos: 109, 251 y 263. No lo son: 161 = 7×23 y 221 = 13×17. Son 3 primos.",
        "dificultad": 3,
    },
    {
        "tema": "Poliedros: vértices, caras y aristas",
        "enunciado": "En un prisma triangular, ¿cuánto suman el número de vértices, caras y aristas (V + C + A)?",
        "correcta": "20",
        "distractores": ["18", "21", "24"],
        "explicacion": "Un prisma triangular tiene 6 vértices, 5 caras y 9 aristas: 6 + 5 + 9 = 20.",
        "dificultad": 2,
    },
    {
        "tema": "Logística: número de viajes",
        "enunciado": "Un camión puede transportar 18 cajas por viaje. Si hay que mover 72 cajas, ¿cuántos viajes necesita como mínimo?",
        "correcta": "4",
        "distractores": ["3", "5", "6"],
        "explicacion": "72 ÷ 18 = 4 viajes exactos.",
        "dificultad": 1,
    },
    {
        "tema": "Mínimo común múltiplo (MCM)",
        "enunciado": "Tres faros parpadean cada 6, 7 y 8 segundos. Si parpadean juntos ahora, ¿dentro de cuántos segundos volverán a parpadear los tres a la vez?",
        "correcta": "168",
        "distractores": ["336", "84", "42"],
        "explicacion": "Es el MCM de 6, 7 y 8. Como 6=2·3, 7=7 y 8=2³, el MCM = 2³·3·7 = 168 segundos.",
        "dificultad": 3,
    },
    {
        "tema": "Fracción irreducible",
        "enunciado": "En una reunión hay 600 personas y 220 son niños. ¿Qué fracción irreducible del total son niños?",
        "correcta": "11/30",
        "distractores": ["22/60", "2/5", "11/19"],
        "explicacion": "220/600 se simplifica dividiendo entre 20: 11/30.",
        "dificultad": 2,
    },
    {
        "tema": "Calendario (aritmética modular)",
        "enunciado": "Si hoy es martes, ¿qué día de la semana será dentro de 100 días?",
        "correcta": "Jueves",
        "distractores": ["Miércoles", "Viernes", "Lunes"],
        "explicacion": "100 ÷ 7 deja resto 2. Dos días después del martes es jueves.",
        "dificultad": 2,
    },
    {
        "tema": "Promedio de notas",
        "enunciado": "Las notas de Ana en tres pruebas fueron 7, 8 y 12. ¿Cuál es su promedio?",
        "correcta": "9",
        "distractores": ["8", "10", "27"],
        "explicacion": "(7 + 8 + 12) ÷ 3 = 27 ÷ 3 = 9.",
        "dificultad": 1,
    },
    {
        "tema": "Máximo común divisor (MCD)",
        "enunciado": "Se reparten 728 sillas azules y 819 sillas blancas en aulas, con la misma cantidad por aula y sin mezclar colores. ¿Cuál es el mayor número de sillas por aula posible?",
        "correcta": "91",
        "distractores": ["7", "13", "63"],
        "explicacion": "Es el MCD de 728 y 819. Como 728 = 91×8 y 819 = 91×9, el MCD es 91.",
        "dificultad": 3,
    },
    {
        "tema": "Perímetro de un rectángulo",
        "enunciado": "Un rectángulo mide 8 cm de largo y 5 cm de ancho. ¿Cuál es su perímetro?",
        "correcta": "26",
        "distractores": ["40", "13", "18"],
        "explicacion": "Perímetro = 2 × (largo + ancho) = 2 × (8 + 5) = 2 × 13 = 26 cm.",
        "dificultad": 1,
    },
    {
        "tema": "Área de una figura compuesta",
        "enunciado": "Una figura en forma de L se hace con un rectángulo de 6×4 al que se le quita un cuadrado de 2×2. ¿Cuál es el área de la L?",
        "correcta": "20",
        "distractores": ["24", "16", "28"],
        "explicacion": "Área del rectángulo: 6×4 = 24. Se quita el cuadrado 2×2 = 4. Área de la L: 24 − 4 = 20.",
        "dificultad": 2,
    },
    {
        "tema": "Redondeo por exceso (compra de latas)",
        "enunciado": "Para pintar una pared se necesitan 13 litros de pintura y cada lata trae 5 litros. ¿Cuántas latas hay que comprar?",
        "correcta": "3",
        "distractores": ["2", "4", "13"],
        "explicacion": "13 ÷ 5 = 2 latas y sobran 3 litros por cubrir, así que hay que comprar 3 latas enteras.",
        "dificultad": 2,
    },
    {
        "tema": "Fracciones continuas",
        "enunciado": "¿Cuánto vale la expresión 1 + 1/(2 + 1/2)?",
        "correcta": "7/5",
        "distractores": ["5/7", "3/2", "2/5"],
        "explicacion": "2 + 1/2 = 5/2. Entonces 1/(5/2) = 2/5. Y 1 + 2/5 = 7/5.",
        "dificultad": 3,
    },
    {
        "tema": "Potencias de 10 con decimales",
        "enunciado": "¿Cuánto es 3,5 × 1000?",
        "correcta": "3500",
        "distractores": ["350", "35000", "35"],
        "explicacion": "Multiplicar por 1000 corre la coma 3 lugares a la derecha: 3,5 → 3500.",
        "dificultad": 1,
    },
    # ── Preguntas REALES del banco CMRJ / Colégio Pedro II (traducidas al
    #    español y verificadas). Origen: Pedro II/04_Banco_Transcribido. ──
    {
        "tema": "Fracción del resto (multi-paso)",
        "enunciado": "Un mayorista tenía 2600 sacas de arroz. Vendió 4/13 a un primer cliente; de lo que sobró vendió 1/3 a un segundo; de lo que sobró vendió 3/10 a un tercero. ¿Cuántas sacas le sobraron?",
        "correcta": "840",
        "distractores": ["800", "1200", "600"],
        "explicacion": "4/13 de 2600 = 800 (quedan 1800). 1/3 de 1800 = 600 (quedan 1200). 3/10 de 1200 = 360 (quedan 840).",
        "dificultad": 3,
    },
    {
        "tema": "Cadena de fracciones",
        "enunciado": "Calcula 4/7 de 3/4 de 14/9 de 21.",
        "correcta": "14",
        "distractores": ["12", "21", "7"],
        "explicacion": "4/7 × 3/4 = 3/7; 3/7 × 14/9 = 2/3; 2/3 × 21 = 14.",
        "dificultad": 3,
    },
    {
        "tema": "Problema inverso del salario",
        "enunciado": "Gasté 1/5 de mi salario en comida y 2/3 de lo que sobró en otros gastos. Me quedaron R$ 160. ¿Cuál era mi salario?",
        "correcta": "R$ 600",
        "distractores": ["R$ 800", "R$ 480", "R$ 720"],
        "explicacion": "Tras comida queda 4/5. Otros gastos: 2/3 de 4/5 = 8/15. Sobra 4/15 del salario = 160, así que el salario = 160 × 15/4 = 600.",
        "dificultad": 3,
    },
    {
        "tema": "Fracción impropia a número mixto",
        "enunciado": "Transforma la fracción impropia 11/5 en número mixto.",
        "correcta": "2 1/5",
        "distractores": ["1 6/5", "2 2/5", "3 1/5"],
        "explicacion": "11 ÷ 5 = 2 con resto 1, entonces 11/5 = 2 enteros y 1/5.",
        "dificultad": 2,
    },
    {
        "tema": "Máximo común divisor (Euclides)",
        "enunciado": "¿Cuál es el MDC (máximo común divisor) de 1200 y 540?",
        "correcta": "60",
        "distractores": ["120", "30", "90"],
        "explicacion": "1200 = 2×540 + 120; 540 = 4×120 + 60; 120 = 2×60. El último resto no nulo es 60.",
        "dificultad": 3,
    },
    {
        "tema": "Propiedad MDC × MMC",
        "enunciado": "El MDC de dos números es 24 y su MMC es 600. Si uno de los números es 120, ¿cuál es el otro?",
        "correcta": "120",
        "distractores": ["144", "100", "150"],
        "explicacion": "MDC × MMC = producto de los números: 24 × 600 = 120 × x, entonces x = 14400 ÷ 120 = 120.",
        "dificultad": 3,
    },
    {
        "tema": "Criterios de divisibilidad",
        "enunciado": "En el número 4A47B, ¿qué cifras A y B lo hacen divisible a la vez por 2, 5, 9 y 10?",
        "correcta": "A=3, B=0",
        "distractores": ["A=0, B=0", "A=3, B=5", "A=6, B=0"],
        "explicacion": "Para ÷2, 5 y 10, B=0. Para ÷9, 4+A+4+7+0 = 15+A debe ser múltiplo de 9, así que A=3 (18).",
        "dificultad": 3,
    },
    {
        "tema": "Relación de Euler (poliedros)",
        "enunciado": "Un poliedro tiene 8 vértices y 12 aristas. Según la relación de Euler (V + C = A + 2), ¿cuántas caras tiene?",
        "correcta": "6",
        "distractores": ["4", "8", "5"],
        "explicacion": "C = A + 2 − V = 12 + 2 − 8 = 6 caras.",
        "dificultad": 3,
    },
    {
        "tema": "Volumen y capacidad",
        "enunciado": "¿Cuántos litros de agua caben en un depósito cúbico de 1 metro de arista?",
        "correcta": "1000",
        "distractores": ["100", "10000", "1"],
        "explicacion": "1 m³ = 1000 dm³, y 1 dm³ = 1 litro, así que caben 1000 litros.",
        "dificultad": 2,
    },
    {
        "tema": "Balanza en equilibrio",
        "enunciado": "Una balanza está en equilibrio con 3 sandías iguales de un lado y 1 sandía más una pesa de 4 kg del otro. ¿Cuánto pesa cada sandía?",
        "correcta": "2 kg",
        "distractores": ["4 kg", "6 kg", "1 kg"],
        "explicacion": "3 sandías = 1 sandía + 4 kg, entonces 2 sandías = 4 kg, así que cada sandía pesa 2 kg.",
        "dificultad": 3,
    },
    {
        "tema": "Área total (planta)",
        "enunciado": "Un apartamento tiene: sala 24 m², cuarto 1 15 m², cuarto 2 12 m², cocina 9 m² y baño 4 m². ¿Cuál es el área total?",
        "correcta": "64",
        "distractores": ["60", "66", "54"],
        "explicacion": "24 + 15 + 12 + 9 + 4 = 64 m².",
        "dificultad": 2,
    },
    {
        "tema": "Área de una corona circular",
        "enunciado": "Una piscina circular de radio 3 m tiene alrededor una vereda de 1 m de ancho. ¿Cuál es el área de la vereda? (π = 3,14)",
        "correcta": "21,98 m²",
        "distractores": ["28,26 m²", "50,24 m²", "12,56 m²"],
        "explicacion": "Círculo grande: 3,14 × 4² = 50,24. Piscina: 3,14 × 3² = 28,26. Vereda = 50,24 − 28,26 = 21,98 m².",
        "dificultad": 3,
    },
    {
        "tema": "Perímetro",
        "enunciado": "Una mesa de ping-pong mide 274 cm de largo y 152 cm de ancho. ¿Cuál es su perímetro?",
        "correcta": "852 cm",
        "distractores": ["426 cm", "800 cm", "904 cm"],
        "explicacion": "Perímetro = 2 × (274 + 152) = 2 × 426 = 852 cm.",
        "dificultad": 2,
    },
    {
        "tema": "Tiempo (sistema sexagesimal)",
        "enunciado": "Una escuela tiene 5 clases de 50 minutos cada una y un recreo de 20 minutos. ¿Cuánto tiempo permanece el alumno en la escuela?",
        "correcta": "4h 30min",
        "distractores": ["5h", "4h", "3h 50min"],
        "explicacion": "5 × 50 + 20 = 270 minutos = 4 horas y 30 minutos.",
        "dificultad": 2,
    },
    {
        "tema": "Grifos que llenan un tanque",
        "enunciado": "Dos grifos llenan juntos un tanque en 3 horas. El primero, solo, tarda 5 horas. ¿Cuánto tarda el segundo grifo solo?",
        "correcta": "7h 30min",
        "distractores": ["2h", "8h", "15h"],
        "explicacion": "En 1 hora los dos llenan 1/3; el primero llena 1/5. El segundo: 1/3 − 1/5 = 2/15 por hora, así que tarda 15/2 = 7,5 h = 7h 30min.",
        "dificultad": 3,
    },
    {
        "tema": "Gráfico de sectores (%)",
        "enunciado": "En una ciudad de 10 000 habitantes, el 49% tiene sangre tipo O. ¿Cuántas personas son tipo O?",
        "correcta": "4900",
        "distractores": ["4090", "5100", "490"],
        "explicacion": "49% de 10 000 = 0,49 × 10 000 = 4900 personas.",
        "dificultad": 2,
    },
    {
        "tema": "Conteo de posibilidades (dados)",
        "enunciado": "Al lanzar dos dados de 6 caras, ¿de cuántas maneras distintas la suma de los puntos puede ser igual a 5?",
        "correcta": "4",
        "distractores": ["3", "5", "2"],
        "explicacion": "Las combinaciones son (1,4), (2,3), (3,2) y (4,1): 4 maneras.",
        "dificultad": 2,
    },
    {
        "tema": "Aumento porcentual",
        "enunciado": "El salario de Roberval era R$ 950. Recibió un aumento del 30%. ¿Cuál es su nuevo salario?",
        "correcta": "R$ 1235",
        "distractores": ["R$ 285", "R$ 1250", "R$ 980"],
        "explicacion": "Aumento: 30% de 950 = 285. Nuevo salario = 950 + 285 = 1235.",
        "dificultad": 2,
    },
    {
        "tema": "Porcentaje de una cantidad",
        "enunciado": "¿Cuánto es el 40% de 48 metros?",
        "correcta": "19,2 m",
        "distractores": ["4,8 m", "24 m", "12 m"],
        "explicacion": "40% de 48 = 0,40 × 48 = 19,2 metros.",
        "dificultad": 2,
    },
]
