"""
Banco de preguntas de los Simulados (Fase 9 - "Simulados Colegio Pedro II").

Reemplaza el stub anterior (3 preguntas hardcodeadas -- una en portugués e
incontestable -- repetidas al azar 200 veces). Las 20 preguntas están basadas
en el análisis matricial del examen real de admisión al 6º año del Colégio
Militar do Rio de Janeiro (ver `coelgiomilitar.md` en la raíz del repo),
adaptadas al español y a un nivel resoluble con cálculo (opción múltiple).

Cada pregunta lleva su respuesta correcta VERIFICADA, 3 distractores
pedagógicos (varios encarnan las "trampas" descritas en el análisis) y una
explicación breve. El seeder combina correcta + distractores y los baraja de
forma determinista por sección, garantizando 10 preguntas DISTINTAS por
simulacro y variedad entre secciones.
"""

# tema | enunciado | correcta | distractores(3) | explicacion | dificultad(1-3)
BANCO_SIMULADOS = [
    {
        "tema": "Estadística: media aritmética",
        "enunciado": "Un gráfico de barras muestra las temperaturas de 5 días: 18, 20, 22, 19 y 21 °C. ¿Cuál fue la temperatura media?",
        "correcta": "20",
        "distractores": ["19", "21", "22"],
        "explicacion": "Suma los 5 valores (18+20+22+19+21 = 100) y divide entre 5: 100 ÷ 5 = 20 °C.",
        "dificultad": 1,
    },
    {
        "tema": "Sistema métrico decimal",
        "enunciado": "Mariana entrenó corriendo 2 km, después 1500 m y después 30000 cm. ¿Cuántos metros corrió en total?",
        "correcta": "3800",
        "distractores": ["3350", "3500", "33500"],
        "explicacion": "Convierte todo a metros: 2 km = 2000 m, 1500 m = 1500 m, 30000 cm = 300 m. Total: 2000+1500+300 = 3800 m.",
        "dificultad": 2,
    },
    {
        "tema": "Fracciones de una cantidad (dinero)",
        "enunciado": "Tito guardó 360 monedas. 1/3 son de R$1, 1/4 son de R$0,50 y 1/6 son de R$0,25. El resto son de R$0,10. ¿Cuántas monedas de R$0,10 tiene?",
        "correcta": "90",
        "distractores": ["60", "120", "72"],
        "explicacion": "1/3 de 360 = 120; 1/4 = 90; 1/6 = 60. Suman 270. El resto: 360 − 270 = 90 monedas.",
        "dificultad": 2,
    },
    {
        "tema": "Porcentaje del remanente",
        "enunciado": "Ana gastó 3/5 de su dinero en libros y el 20% de lo que le quedó en transporte. Si tenía R$200, ¿cuánto gastó en transporte?",
        "correcta": "R$ 16",
        "distractores": ["R$ 40", "R$ 24", "R$ 80"],
        "explicacion": "En libros gastó 3/5 de 200 = 120, le quedaron 80. El 20% de 80 = 16.",
        "dificultad": 3,
    },
    {
        "tema": "Geometría espacial: cubo pintado",
        "enunciado": "Un cubo de 3×3×3 (27 cubitos) se pinta por fuera y luego se separa en cubitos. ¿Cuántos cubitos tienen exactamente 2 caras pintadas?",
        "correcta": "12",
        "distractores": ["8", "6", "4"],
        "explicacion": "Los cubitos con 2 caras pintadas están en las aristas (sin las esquinas). Un cubo tiene 12 aristas y en cada una hay 1 cubito central: 12.",
        "dificultad": 3,
    },
    {
        "tema": "Números romanos",
        "enunciado": "Un número de cuatro cifras es 2358. ¿Cómo se escribe su mitad en números romanos?",
        "correcta": "MCLXXIX",
        "distractores": ["MCXCIX", "MCLXXVIIII", "MDCLXXIX"],
        "explicacion": "La mitad de 2358 es 1179 = 1000 (M) + 100 (C) + 50 (L) + 20 (XX) + 9 (IX) = MCLXXIX.",
        "dificultad": 3,
    },
    {
        "tema": "Razonamiento espacial: el dado",
        "enunciado": "En un dado común, las caras opuestas suman 7. Si una cara muestra 2 puntos, ¿cuántos puntos tiene la cara opuesta?",
        "correcta": "5",
        "distractores": ["6", "4", "7"],
        "explicacion": "Caras opuestas suman 7, entonces la opuesta al 2 es 7 − 2 = 5.",
        "dificultad": 1,
    },
    {
        "tema": "Números primos",
        "enunciado": "¿Cuántos de estos números son primos: 109, 161, 221, 251, 263?",
        "correcta": "3",
        "distractores": ["2", "4", "5"],
        "explicacion": "Primos: 109, 251 y 263. No lo son: 161 = 7×23 y 221 = 13×17. Son 3 primos.",
        "dificultad": 3,
    },
    {
        "tema": "Poliedros: vértices, caras y aristas",
        "enunciado": "En un prisma triangular, ¿cuánto suman el número de vértices, caras y aristas (V + C + A)?",
        "correcta": "20",
        "distractores": ["18", "21", "24"],
        "explicacion": "Un prisma triangular tiene 6 vértices, 5 caras y 9 aristas: 6 + 5 + 9 = 20.",
        "dificultad": 2,
    },
    {
        "tema": "Logística: número de viajes",
        "enunciado": "Un camión puede transportar 18 cajas por viaje. Si hay que mover 72 cajas, ¿cuántos viajes necesita como mínimo?",
        "correcta": "4",
        "distractores": ["3", "5", "6"],
        "explicacion": "72 ÷ 18 = 4 viajes exactos.",
        "dificultad": 1,
    },
    {
        "tema": "Mínimo común múltiplo (MCM)",
        "enunciado": "Tres faros parpadean cada 6, 7 y 8 segundos. Si parpadean juntos ahora, ¿dentro de cuántos segundos volverán a parpadear los tres a la vez?",
        "correcta": "168",
        "distractores": ["336", "84", "42"],
        "explicacion": "Es el MCM de 6, 7 y 8. Como 6=2·3, 7=7 y 8=2³, el MCM = 2³·3·7 = 168 segundos.",
        "dificultad": 3,
    },
    {
        "tema": "Fracción irreducible",
        "enunciado": "En una reunión hay 600 personas y 220 son niños. ¿Qué fracción irreducible del total son niños?",
        "correcta": "11/30",
        "distractores": ["22/60", "2/5", "11/19"],
        "explicacion": "220/600 se simplifica dividiendo entre 20: 11/30.",
        "dificultad": 2,
    },
    {
        "tema": "Calendario (aritmética modular)",
        "enunciado": "Si hoy es martes, ¿qué día de la semana será dentro de 100 días?",
        "correcta": "Jueves",
        "distractores": ["Miércoles", "Viernes", "Lunes"],
        "explicacion": "100 ÷ 7 deja resto 2. Dos días después del martes es jueves.",
        "dificultad": 2,
    },
    {
        "tema": "Promedio de notas",
        "enunciado": "Las notas de Ana en tres pruebas fueron 7, 8 y 12. ¿Cuál es su promedio?",
        "correcta": "9",
        "distractores": ["8", "10", "27"],
        "explicacion": "(7 + 8 + 12) ÷ 3 = 27 ÷ 3 = 9.",
        "dificultad": 1,
    },
    {
        "tema": "Máximo común divisor (MCD)",
        "enunciado": "Se reparten 728 sillas azules y 819 sillas blancas en aulas, con la misma cantidad por aula y sin mezclar colores. ¿Cuál es el mayor número de sillas por aula posible?",
        "correcta": "91",
        "distractores": ["7", "13", "63"],
        "explicacion": "Es el MCD de 728 y 819. Como 728 = 91×8 y 819 = 91×9, el MCD es 91.",
        "dificultad": 3,
    },
    {
        "tema": "Perímetro de un rectángulo",
        "enunciado": "Un rectángulo mide 8 cm de largo y 5 cm de ancho. ¿Cuál es su perímetro?",
        "correcta": "26",
        "distractores": ["40", "13", "18"],
        "explicacion": "Perímetro = 2 × (largo + ancho) = 2 × (8 + 5) = 2 × 13 = 26 cm.",
        "dificultad": 1,
    },
    {
        "tema": "Área de una figura compuesta",
        "enunciado": "Una figura en forma de L se hace con un rectángulo de 6×4 al que se le quita un cuadrado de 2×2. ¿Cuál es el área de la L?",
        "correcta": "20",
        "distractores": ["24", "16", "28"],
        "explicacion": "Área del rectángulo: 6×4 = 24. Se quita el cuadrado 2×2 = 4. Área de la L: 24 − 4 = 20.",
        "dificultad": 2,
    },
    {
        "tema": "Redondeo por exceso (compra de latas)",
        "enunciado": "Para pintar una pared se necesitan 13 litros de pintura y cada lata trae 5 litros. ¿Cuántas latas hay que comprar?",
        "correcta": "3",
        "distractores": ["2", "4", "13"],
        "explicacion": "13 ÷ 5 = 2 latas y sobran 3 litros por cubrir, así que hay que comprar 3 latas enteras.",
        "dificultad": 2,
    },
    {
        "tema": "Fracciones continuas",
        "enunciado": "¿Cuánto vale la expresión 1 + 1/(2 + 1/2)?",
        "correcta": "7/5",
        "distractores": ["5/7", "3/2", "2/5"],
        "explicacion": "2 + 1/2 = 5/2. Entonces 1/(5/2) = 2/5. Y 1 + 2/5 = 7/5.",
        "dificultad": 3,
    },
    {
        "tema": "Potencias de 10 con decimales",
        "enunciado": "¿Cuánto es 3,5 × 1000?",
        "correcta": "3500",
        "distractores": ["350", "35000", "35"],
        "explicacion": "Multiplicar por 1000 corre la coma 3 lugares a la derecha: 3,5 → 3500.",
        "dificultad": 1,
    },
    # ── Preguntas REALES del banco CMRJ / Colégio Pedro II (traducidas al
    #    español y verificadas). Origen: Pedro II/04_Banco_Transcribido. ──
    {
        "tema": "Fracción del resto (multi-paso)",
        "enunciado": "Un mayorista tenía 2600 sacas de arroz. Vendió 4/13 a un primer cliente; de lo que sobró vendió 1/3 a un segundo; de lo que sobró vendió 3/10 a un tercero. ¿Cuántas sacas le sobraron?",
        "correcta": "840",
        "distractores": ["800", "1200", "600"],
        "explicacion": "4/13 de 2600 = 800 (quedan 1800). 1/3 de 1800 = 600 (quedan 1200). 3/10 de 1200 = 360 (quedan 840).",
        "dificultad": 3,
    },
    {
        "tema": "Cadena de fracciones",
        "enunciado": "Calcula 4/7 de 3/4 de 14/9 de 21.",
        "correcta": "14",
        "distractores": ["12", "21", "7"],
        "explicacion": "4/7 × 3/4 = 3/7; 3/7 × 14/9 = 2/3; 2/3 × 21 = 14.",
        "dificultad": 3,
    },
    {
        "tema": "Problema inverso del salario",
        "enunciado": "Gasté 1/5 de mi salario en comida y 2/3 de lo que sobró en otros gastos. Me quedaron R$ 160. ¿Cuál era mi salario?",
        "correcta": "R$ 600",
        "distractores": ["R$ 800", "R$ 480", "R$ 720"],
        "explicacion": "Tras comida queda 4/5. Otros gastos: 2/3 de 4/5 = 8/15. Sobra 4/15 del salario = 160, así que el salario = 160 × 15/4 = 600.",
        "dificultad": 3,
    },
    {
        "tema": "Fracción impropia a número mixto",
        "enunciado": "Transforma la fracción impropia 11/5 en número mixto.",
        "correcta": "2 1/5",
        "distractores": ["1 6/5", "2 2/5", "3 1/5"],
        "explicacion": "11 ÷ 5 = 2 con resto 1, entonces 11/5 = 2 enteros y 1/5.",
        "dificultad": 2,
    },
    {
        "tema": "Máximo común divisor (Euclides)",
        "enunciado": "¿Cuál es el MDC (máximo común divisor) de 1200 y 540?",
        "correcta": "60",
        "distractores": ["120", "30", "90"],
        "explicacion": "1200 = 2×540 + 120; 540 = 4×120 + 60; 120 = 2×60. El último resto no nulo es 60.",
        "dificultad": 3,
    },
    {
        "tema": "Propiedad MDC × MMC",
        "enunciado": "El MDC de dos números es 24 y su MMC es 600. Si uno de los números es 120, ¿cuál es el otro?",
        "correcta": "120",
        "distractores": ["144", "100", "150"],
        "explicacion": "MDC × MMC = producto de los números: 24 × 600 = 120 × x, entonces x = 14400 ÷ 120 = 120.",
        "dificultad": 3,
    },
    {
        "tema": "Criterios de divisibilidad",
        "enunciado": "En el número 4A47B, ¿qué cifras A y B lo hacen divisible a la vez por 2, 5, 9 y 10?",
        "correcta": "A=3, B=0",
        "distractores": ["A=0, B=0", "A=3, B=5", "A=6, B=0"],
        "explicacion": "Para ÷2, 5 y 10, B=0. Para ÷9, 4+A+4+7+0 = 15+A debe ser múltiplo de 9, así que A=3 (18).",
        "dificultad": 3,
    },
    {
        "tema": "Relación de Euler (poliedros)",
        "enunciado": "Un poliedro tiene 8 vértices y 12 aristas. Según la relación de Euler (V + C = A + 2), ¿cuántas caras tiene?",
        "correcta": "6",
        "distractores": ["4", "8", "5"],
        "explicacion": "C = A + 2 − V = 12 + 2 − 8 = 6 caras.",
        "dificultad": 3,
    },
    {
        "tema": "Volumen y capacidad",
        "enunciado": "¿Cuántos litros de agua caben en un depósito cúbico de 1 metro de arista?",
        "correcta": "1000",
        "distractores": ["100", "10000", "1"],
        "explicacion": "1 m³ = 1000 dm³, y 1 dm³ = 1 litro, así que caben 1000 litros.",
        "dificultad": 2,
    },
    {
        "tema": "Balanza en equilibrio",
        "enunciado": "Una balanza está en equilibrio con 3 sandías iguales de un lado y 1 sandía más una pesa de 4 kg del otro. ¿Cuánto pesa cada sandía?",
        "correcta": "2 kg",
        "distractores": ["4 kg", "6 kg", "1 kg"],
        "explicacion": "3 sandías = 1 sandía + 4 kg, entonces 2 sandías = 4 kg, así que cada sandía pesa 2 kg.",
        "dificultad": 3,
    },
    {
        "tema": "Área total (planta)",
        "enunciado": "Un apartamento tiene: sala 24 m², cuarto 1 15 m², cuarto 2 12 m², cocina 9 m² y baño 4 m². ¿Cuál es el área total?",
        "correcta": "64",
        "distractores": ["60", "66", "54"],
        "explicacion": "24 + 15 + 12 + 9 + 4 = 64 m².",
        "dificultad": 2,
    },
    {
        "tema": "Área de una corona circular",
        "enunciado": "Una piscina circular de radio 3 m tiene alrededor una vereda de 1 m de ancho. ¿Cuál es el área de la vereda? (π = 3,14)",
        "correcta": "21,98 m²",
        "distractores": ["28,26 m²", "50,24 m²", "12,56 m²"],
        "explicacion": "Círculo grande: 3,14 × 4² = 50,24. Piscina: 3,14 × 3² = 28,26. Vereda = 50,24 − 28,26 = 21,98 m².",
        "dificultad": 3,
    },
    {
        "tema": "Perímetro",
        "enunciado": "Una mesa de ping-pong mide 274 cm de largo y 152 cm de ancho. ¿Cuál es su perímetro?",
        "correcta": "852 cm",
        "distractores": ["426 cm", "800 cm", "904 cm"],
        "explicacion": "Perímetro = 2 × (274 + 152) = 2 × 426 = 852 cm.",
        "dificultad": 2,
    },
    {
        "tema": "Tiempo (sistema sexagesimal)",
        "enunciado": "Una escuela tiene 5 clases de 50 minutos cada una y un recreo de 20 minutos. ¿Cuánto tiempo permanece el alumno en la escuela?",
        "correcta": "4h 30min",
        "distractores": ["5h", "4h", "3h 50min"],
        "explicacion": "5 × 50 + 20 = 270 minutos = 4 horas y 30 minutos.",
        "dificultad": 2,
    },
    {
        "tema": "Grifos que llenan un tanque",
        "enunciado": "Dos grifos llenan juntos un tanque en 3 horas. El primero, solo, tarda 5 horas. ¿Cuánto tarda el segundo grifo solo?",
        "correcta": "7h 30min",
        "distractores": ["2h", "8h", "15h"],
        "explicacion": "En 1 hora los dos llenan 1/3; el primero llena 1/5. El segundo: 1/3 − 1/5 = 2/15 por hora, así que tarda 15/2 = 7,5 h = 7h 30min.",
        "dificultad": 3,
    },
    {
        "tema": "Gráfico de sectores (%)",
        "enunciado": "En una ciudad de 10 000 habitantes, el 49% tiene sangre tipo O. ¿Cuántas personas son tipo O?",
        "correcta": "4900",
        "distractores": ["4090", "5100", "490"],
        "explicacion": "49% de 10 000 = 0,49 × 10 000 = 4900 personas.",
        "dificultad": 2,
    },
    {
        "tema": "Conteo de posibilidades (dados)",
        "enunciado": "Al lanzar dos dados de 6 caras, ¿de cuántas maneras distintas la suma de los puntos puede ser igual a 5?",
        "correcta": "4",
        "distractores": ["3", "5", "2"],
        "explicacion": "Las combinaciones son (1,4), (2,3), (3,2) y (4,1): 4 maneras.",
        "dificultad": 2,
    },
    {
        "tema": "Aumento porcentual",
        "enunciado": "El salario de Roberval era R$ 950. Recibió un aumento del 30%. ¿Cuál es su nuevo salario?",
        "correcta": "R$ 1235",
        "distractores": ["R$ 285", "R$ 1250", "R$ 980"],
        "explicacion": "Aumento: 30% de 950 = 285. Nuevo salario = 950 + 285 = 1235.",
        "dificultad": 2,
    },
    {
        "tema": "Porcentaje de una cantidad",
        "enunciado": "¿Cuánto es el 40% de 48 metros?",
        "correcta": "19,2 m",
        "distractores": ["4,8 m", "24 m", "12 m"],
        "explicacion": "40% de 48 = 0,40 × 48 = 19,2 metros.",
        "dificultad": 2,
    },

    # ==========================================================================
    # EXAMEN REAL CMRJ - MATEMÁTICA 2019/2020 (prova de admissão ao 6º ano)
    # 18 preguntas traducidas al español y VERIFICADAS a mano (cálculo reproducido).
    # Se omiten Q03 (planta de casa) y Q19 (cancha de tenis) por depender de una
    # figura no reconstruible en texto -> pendientes de SVG propio.
    # Cada una conserva los 5 distractores/alternativas originales del examen.
    # ==========================================================================
    {
        "tema": "Expresiones con fracciones y decimales",
        "origen": "CMRJ 2019 - Q01",
        "enunciado": "Sabiendo que A = 21 · [4/9 · (5/4 − 1/2)] + 2/5 ÷ 3/10 y que B = 1/5 ÷ (1 − 0,8) − 4/3 · (1/4 + 0,25), el cociente A/B es un número:",
        "correcta": "Impar y múltiplo de 5",
        "distractores": ["Par y divisible por 11", "Par y múltiplo de 3", "Divisible por 9", "Primo"],
        "explicacion": "A = 21·(1/3) + (2/5·10/3) = 7 + 4/3 = 25/3. B = (1/5÷0,2) − (4/3·1/2) = 1 − 2/3 = 1/3. A/B = (25/3)÷(1/3) = 25, que es impar y múltiplo de 5.",
        "dificultad": 3,
    },
    {
        "tema": "Diferencia de cuadrados (razonamiento)",
        "origen": "CMRJ 2019 - Q02",
        "enunciado": "Piensa en dos números de una sola cifra, uno impar y otro par (distinto de cero). Suma esos números, calcula su diferencia y multiplica la suma por la diferencia. Si el resultado es 77, ¿cuál es el mayor de los dos números?",
        "correcta": "9",
        "distractores": ["8", "7", "6", "5"],
        "explicacion": "(a+b)·(a−b) = a² − b² = 77. Como 9² − 2² = 81 − 4 = 77, los números son 9 y 2; el mayor es 9.",
        "dificultad": 3,
    },
    {
        "tema": "Operaciones con símbolos (descifrar)",
        "origen": "CMRJ 2019 - Q04",
        "enunciado": "Tres operaciones básicas se representan con los símbolos ★, ◆ y ●. Se sabe que 2 ● 3 = 6, que 12 ◆ 4 = 3 y que 2 ★ 3 ★ 6 = 11. Calcula el valor de: 500 ◆ {2 ● [(13 ★ 8) ◆ 3 ★ 20 ● 5 ★ 108 ◆ 6]}.",
        "correcta": "2",
        "distractores": ["1", "3", "4", "5"],
        "explicacion": "● es ×, ◆ es ÷ y ★ es +. Entonces 500 ÷ {2 × [(21÷3) + (20×5) + (108÷6)]} = 500 ÷ {2 × [7 + 100 + 18]} = 500 ÷ 250 = 2.",
        "dificultad": 3,
    },
    {
        "tema": "Volumen del paralelepípedo",
        "origen": "CMRJ 2019 - Q05",
        "enunciado": "Una piscina con forma de paralelepípedo tiene 21.000 dm³ de volumen, 100 cm de altura y 3,5 m de ancho. ¿Cuál es la medida de su largo?",
        "correcta": "6 m",
        "distractores": ["7 m", "8 m", "9 m", "10 m"],
        "explicacion": "Todo a decímetros: altura = 10 dm, ancho = 35 dm. Largo = 21.000 ÷ (10 × 35) = 21.000 ÷ 350 = 60 dm = 6 m.",
        "dificultad": 2,
    },
    {
        "tema": "Restos y múltiplos comunes",
        "origen": "CMRJ 2019 - Q06",
        "enunciado": "El número total de huevos es mayor que 200 y menor que 400. Contándolos de 2 en 2, de 3 en 3, de 4 en 4, de 5 en 5 y de 6 en 6 siempre sobra 1; pero de 7 en 7 no sobra ninguno. Si se venden 7 huevos por R$ 8,50, ¿cuánto valen todos los huevos?",
        "correcta": "R$ 365,50",
        "distractores": ["R$ 340,00", "R$ 370,00", "R$ 325,50", "R$ 385,50"],
        "explicacion": "El número menos 1 es múltiplo de 2,3,4,5 y 6, es decir múltiplo de 60. Entre 200 y 400: 241, 301 y 361. El único múltiplo de 7 es 301. Son 301 ÷ 7 = 43 grupos × R$ 8,50 = R$ 365,50.",
        "dificultad": 3,
    },
    {
        "tema": "Sistema de igualdades (pesos)",
        "origen": "CMRJ 2019 - Q07",
        "enunciado": "3 melones y 8 mangos pesan en total 5.000 gramos. Si un melón pesa lo mismo que 4 mangos, ¿cuánto pesa cada melón?",
        "correcta": "1 kg",
        "distractores": ["250 g", "0,85 kg", "900 g", "0,75 kg"],
        "explicacion": "1 melón = 4 mangos, así que 3 melones = 12 mangos. 12 + 8 = 20 mangos = 5.000 g → 1 mango = 250 g. Melón = 4 × 250 = 1.000 g = 1 kg.",
        "dificultad": 2,
    },
    {
        "tema": "Máximo común divisor (baldosas)",
        "origen": "CMRJ 2019 - Q08",
        "enunciado": "Una sala de 3,36 m de ancho por 4,00 m de largo se cubrirá con piezas cerámicas cuadradas e iguales, sin recortes ni sobras. Usando la menor cantidad posible de piezas, ese número es:",
        "correcta": "Igual a 525",
        "distractores": ["Impar y menor que 500", "Múltiplo de 10", "Mayor que 570", "Primo"],
        "explicacion": "El lado de la pieza es el mcd de 336 cm y 400 cm = 16 cm. Se necesitan (336÷16) × (400÷16) = 21 × 25 = 525 piezas.",
        "dificultad": 3,
    },
    {
        "tema": "Porcentaje de porcentaje",
        "origen": "CMRJ 2019 - Q09",
        "enunciado": "Un restaurante tiene 88 fotografías en sus paredes; el 50% están autografiadas. De las autografiadas, el 25% son a color. ¿Cuántas fotografías autografiadas NO son a color?",
        "correcta": "33",
        "distractores": ["77", "44", "22", "11"],
        "explicacion": "50% de 88 = 44 autografiadas. 25% de 44 = 11 a color. No a color: 44 − 11 = 33.",
        "dificultad": 2,
    },
    {
        "tema": "Fracciones de una población",
        "origen": "CMRJ 2019 - Q10",
        "enunciado": "En una ciudad de 1,2 millón de habitantes, 1/20 de la población se infectó de una enfermedad. De los infectados, 1/10 tuvo problemas de visión. ¿Cuántas personas tuvieron problemas de visión?",
        "correcta": "6.000",
        "distractores": ["3.000", "4.000", "5.000", "12.000"],
        "explicacion": "1/20 de 1.200.000 = 60.000 infectados. 1/10 de 60.000 = 6.000 personas.",
        "dificultad": 2,
    },
    {
        "tema": "Reparto con fracciones (ecuación)",
        "origen": "CMRJ 2019 - Q11",
        "enunciado": "Se repartieron cajas de leche entre 4 familias. La familia C recibió 1/2 del total; la M, 2/7; la R, 1/14; y el resto fue para la familia J. Después, C donó 15 cajas a R, y entonces C y M quedaron con la misma cantidad. ¿Cuántas cajas recibió la familia J?",
        "correcta": "10",
        "distractores": ["5", "15", "20", "25"],
        "explicacion": "C − 15 = M → (1/2 − 2/7)·T = 15 → (3/14)·T = 15 → T = 70. J recibe 1 − (1/2 + 2/7 + 1/14) = 1/7 del total = 70 ÷ 7 = 10.",
        "dificultad": 3,
    },
    {
        "tema": "Calendario y días de la semana",
        "origen": "CMRJ 2019 - Q12",
        "enunciado": "En cierto año, el 6 de mayo cae en sábado. ¿Qué día de la semana será el 25 de diciembre de ese mismo año?",
        "correcta": "Lunes",
        "distractores": ["Sábado", "Domingo", "Martes", "Miércoles"],
        "explicacion": "Del 6 de mayo al 25 de diciembre hay 233 días. Como 233 = 7×33 + 2, caen 2 días después del sábado: lunes.",
        "dificultad": 3,
    },
    {
        "tema": "Mínimo común múltiplo (horarios)",
        "origen": "CMRJ 2019 - Q13",
        "enunciado": "Tres autobuses salen cada 12, 20 y 18 minutos, respectivamente. La última vez que los tres salieron juntos fue a las 15h20min. ¿A qué hora volverán a salir juntos?",
        "correcta": "18h20min",
        "distractores": ["16h20min", "17h15min", "19h15min", "20h20min"],
        "explicacion": "mcm(12, 20, 18) = 180 minutos = 3 horas. 15h20min + 3h = 18h20min.",
        "dificultad": 2,
    },
    {
        "tema": "Recta numérica y segmentos",
        "origen": "CMRJ 2019 - Q14",
        "enunciado": "En una recta numérica, el segmento AF está dividido en 5 partes iguales por los puntos B, C, D y E (AB = BC = CD = DE = EF). Si B corresponde a 9/8 y F a 273/104, ¿qué número corresponde al punto A?",
        "correcta": "0,75",
        "distractores": ["0,6", "0,125", "1", "0,5"],
        "explicacion": "Cada parte mide (F − B) ÷ 4 = (273/104 − 9/8) ÷ 4 = (3/2) ÷ 4 = 3/8. A = B − 3/8 = 9/8 − 3/8 = 6/8 = 0,75.",
        "dificultad": 3,
    },
    {
        "tema": "Combinaciones (torneo)",
        "origen": "CMRJ 2019 - Q15",
        "enunciado": "En un torneo, cada jugador juega una sola vez contra cada uno de los demás. Con 2 jugadores hay 1 partida; con 3, hay 3; con 4, hay 6; con 5, hay 10; con 6, hay 15. Si se inscriben 10 jugadores, el número de partidas será múltiplo de:",
        "correcta": "9",
        "distractores": ["6", "7", "8", "10"],
        "explicacion": "Partidas = 10 × 9 ÷ 2 = 45. Como 45 = 9 × 5, es múltiplo de 9.",
        "dificultad": 2,
    },
    {
        "tema": "Razonamiento lógico (ordenar)",
        "origen": "CMRJ 2019 - Q16",
        "enunciado": "En un grupo de 32 alumnos, todos con estaturas distintas, el niño más bajo es más alto que 3 niñas; el segundo más bajo, más alto que 4 niñas; el tercero, más alto que 5 niñas, y así sucesivamente, hasta que el niño más alto es más alto que todas las niñas. ¿Cuántas niñas hay en el grupo?",
        "correcta": "17",
        "distractores": ["21", "19", "18", "15"],
        "explicacion": "Si hay m niños, el m-ésimo (el más alto) supera a m+2 niñas, que son todas. Entonces niñas = m+2 y m + (m+2) = 32 → m = 15 niños y 17 niñas.",
        "dificultad": 3,
    },
    {
        "tema": "Velocidades y fracciones (encuentro)",
        "origen": "CMRJ 2019 - Q17",
        "enunciado": "Ana empieza a bajar una escalera desde arriba en el mismo instante en que Rebeca empieza a subirla desde abajo, cada una a velocidad constante. Al cruzarse, Ana había bajado 3/4 de la escalera. Cuando Ana termine de bajar toda la escalera, ¿qué fracción le faltará subir a Rebeca para llegar arriba?",
        "correcta": "2/3",
        "distractores": ["3/4", "4/5", "7/12", "1/2"],
        "explicacion": "Al cruzarse, en el mismo tiempo Ana avanzó 3/4 y Rebeca 1/4: Ana es 3 veces más rápida. Cuando Ana completa la escalera (tiempo 4/3 del inicial), Rebeca ha subido 1/3; le falta 1 − 1/3 = 2/3.",
        "dificultad": 3,
    },
    {
        "tema": "Geometría espacial (cubo cortado)",
        "origen": "CMRJ 2019 - Q18",
        "enunciado": "Un cubo de madera se pinta de blanco por toda su superficie y luego se corta en 27 cubitos iguales. Las caras que no quedaron pintadas conservan el color natural de la madera. Considerando los 27 cubitos, ¿cuántas caras están en el color natural de la madera?",
        "correcta": "108",
        "distractores": ["54", "72", "102", "162"],
        "explicacion": "Los 27 cubitos tienen 27 × 6 = 162 caras. La superficie pintada del cubo grande son 6 × 9 = 54 caras. Sin pintar: 162 − 54 = 108.",
        "dificultad": 3,
    },
    {
        "tema": "Lógica con tablas (medallero)",
        "origen": "CMRJ 2019 - Q20",
        "enunciado": "En un medallero (oro, plata, bronce, total) faltan algunos valores. Se sabe: Brasil tiene 55 de oro y 71 de bronce; Chile tiene 50 de total; Perú tiene 39 de total con 21 de bronce; Colombia tiene 28 de oro y 23 de plata; Canadá tiene 35 de oro y 53 de bronce; México tiene 63 de bronce. Además: el total de Chile es el 50% de la suma de oro y plata de Brasil; el total de Canadá es par, múltiplo de 19 y menor que el de Brasil; la plata de Canadá supera al bronce de México; el total de República Dominicana es una medalla más que el de Perú, y tiene 13 de plata y 17 de bronce; el total de Colombia es el cuádruplo del bronce de Perú. Determina, respectivamente, el oro de República Dominicana, la plata de Canadá y el bronce de Colombia.",
        "correcta": "10, 64 y 33",
        "distractores": ["10, 68 y 33", "10, 67 y 37", "15, 66 y 37", "15, 65 y 37"],
        "explicacion": "Chile 50 = 50% de (55 + plata Brasil) → plata Brasil = 45, total Brasil = 171. Canadá par, múltiplo de 19, menor que 171 y con plata > 63 → total 152, plata = 152 − 88 = 64. Rep. Dominicana total = 39 + 1 = 40 → oro = 40 − 13 − 17 = 10. Colombia total = 4 × 21 = 84 → bronce = 84 − 28 − 23 = 33.",
        "dificultad": 3,
    },

    # ==========================================================================
    # EXAMEN REAL CMRJ - MATEMÁTICA 2018 (prova de admissão ao 6º ano)
    # 17 preguntas traducidas y VERIFICADAS a mano. Se omiten Q09 (posiciones en
    # cancha), Q13 (caras de dados) y Q18 (áreas en cuadrícula): dependen de una
    # figura no reconstruible en texto -> pendientes de SVG (D4).
    # ==========================================================================
    {
        "tema": "Factores primos (edad)",
        "origen": "CMRJ 2018 - Q01",
        "enunciado": "Una persona nació el 28 de diciembre de 1922. Al escribir en factores primos el número que representa su edad completa el 28 de diciembre de 2018, ¿qué exponente aparece?",
        "correcta": "5 para el factor 2",
        "distractores": ["3 para el factor 2", "2 para el factor 3", "1 para el factor 5", "2 para el factor 7"],
        "explicacion": "Edad = 2018 − 1922 = 96 = 2⁵ × 3. El factor 2 aparece con exponente 5.",
        "dificultad": 3,
    },
    {
        "tema": "Orden de operaciones",
        "origen": "CMRJ 2018 - Q02",
        "enunciado": "¿Cuál de las siguientes expresiones tiene valor igual a 4?",
        "correcta": "11 × 13 × 15 + 359 − 125 × 20",
        "distractores": ["23 × 32 − 92 × 8", "13 × 21 + 7 − 68 × 4", "32 × 16 − 239 − 91 × 3", "100 + 201 + 302 − 66 × 9"],
        "explicacion": "11×13×15 = 2145 y 125×20 = 2500. Entonces 2145 + 359 − 2500 = 4. Las demás dan 0, 8, 0 y 9.",
        "dificultad": 2,
    },
    {
        "tema": "Criptoaritmética (suma con cifras ocultas)",
        "origen": "CMRJ 2018 - Q03",
        "enunciado": "Al sumar el número de cuatro cifras '1 5 @ 2' con el de tres cifras '* 8 #', el resultado es 2019. Los símbolos @, * y # representan cifras. Escríbelos en orden creciente.",
        "correcta": "3, 4 y 7",
        "distractores": ["2, 4 y 7", "1, 2 y 3", "2, 3 y 7", "4, 5 y 8"],
        "explicacion": "Unidades: 2 + # = 9 → # = 7. Decenas: @ + 8 = 11 → @ = 3 (llevo 1). Centenas: 5 + * + 1 = 10 → * = 4. En orden creciente: 3, 4 y 7.",
        "dificultad": 3,
    },
    {
        "tema": "Fracciones (reparto en partes iguales)",
        "origen": "CMRJ 2018 - Q04",
        "enunciado": "Una armadura se divide en 4 partes con la misma cantidad de metal cada una: cabeza, tronco, los dos miembros superiores y los dos miembros inferiores. Si el metal de la 3ª y la 4ª parte se reparte por igual entre sus dos miembros, ¿qué fracción del metal total usa un miembro inferior?",
        "correcta": "1/8",
        "distractores": ["1/2", "1/3", "1/4", "1/6"],
        "explicacion": "Cada parte es 1/4 del total. La 4ª parte (los dos miembros inferiores) se reparte entre 2: 1/4 ÷ 2 = 1/8.",
        "dificultad": 2,
    },
    {
        "tema": "Velocidad, distancia y tiempo",
        "origen": "CMRJ 2018 - Q05",
        "enunciado": "¿Cuántos minutos tardaría un vehículo en recorrer una pista recta de 4 km a una velocidad de 240 km/h?",
        "correcta": "1",
        "distractores": ["2", "3", "4", "5"],
        "explicacion": "Tiempo = distancia ÷ velocidad = 4 ÷ 240 h = 1/60 h = 1 minuto.",
        "dificultad": 2,
    },
    {
        "tema": "Conteo de eventos periódicos",
        "origen": "CMRJ 2018 - Q06",
        "enunciado": "Un evento se realiza cada 4 años; el primero fue en 1930. Solo en 1942 y 1946 no se realizó. ¿Qué número de edición corresponde al evento de 2022?",
        "correcta": "22",
        "distractores": ["24", "23", "21", "20"],
        "explicacion": "De 1930 a 2022, cada 4 años, hay (2022 − 1930) ÷ 4 + 1 = 24 ediciones posibles. Restando las 2 no realizadas: 24 − 2 = 22.",
        "dificultad": 2,
    },
    {
        "tema": "Multiplicación y suma (aforo)",
        "origen": "CMRJ 2018 - Q07",
        "enunciado": "Dos estadios tuvieron 100% de ocupación en todos sus juegos. Uno tiene capacidad 78.011 y jugó 6 partidos; el otro, capacidad 44.190 y jugó 5 partidos. ¿Cuál fue el público total?",
        "correcta": "689.016",
        "distractores": ["685.432", "687.146", "691.426", "693.356"],
        "explicacion": "78.011 × 6 + 44.190 × 5 = 468.066 + 220.950 = 689.016.",
        "dificultad": 2,
    },
    {
        "tema": "Promedio con descuentos",
        "origen": "CMRJ 2018 - Q08",
        "enunciado": "En un torneo se jugaron 64 partidos con 169 goles en total. Si 12 fueron goles en contra y 22 fueron de penal, ¿cuál es el promedio aproximado de goles por partido sin contar los goles en contra ni los de penal?",
        "correcta": "2,11",
        "distractores": ["2,64", "2,45", "2,32", "2,00"],
        "explicacion": "Goles considerados: 169 − 12 − 22 = 135. Promedio = 135 ÷ 64 ≈ 2,11.",
        "dificultad": 2,
    },
    {
        "tema": "Áreas y conversión de unidades",
        "origen": "CMRJ 2018 - Q10",
        "enunciado": "Un camión transporta por viaje 8 millones de cm² de placas de césped. Para cubrir por completo un campo de 105 m por 68 m, sin pérdidas, ¿cuántos viajes como mínimo debe hacer?",
        "correcta": "9",
        "distractores": ["12", "11", "10", "8"],
        "explicacion": "Área = 105 × 68 = 7.140 m² = 71.400.000 cm². 71.400.000 ÷ 8.000.000 = 8,925 → como mínimo 9 viajes.",
        "dificultad": 2,
    },
    {
        "tema": "Máximo común divisor (canastas)",
        "origen": "CMRJ 2018 - Q11",
        "enunciado": "Se recaudaron 528 kg de azúcar, 240 kg de frijol y 2.016 kg de arroz para armar canastas iguales (cada una con los tres alimentos y la misma cantidad de cada tipo), usando la mayor cantidad posible de canastas. ¿Cuántos kilos de arroz lleva cada canasta?",
        "correcta": "42",
        "distractores": ["11", "20", "31", "48"],
        "explicacion": "El número de canastas es el mcd(528, 240, 2016) = 48. Arroz por canasta: 2.016 ÷ 48 = 42 kg.",
        "dificultad": 3,
    },
    {
        "tema": "Proporcionalidad (receta limitante)",
        "origen": "CMRJ 2018 - Q12",
        "enunciado": "Una receta de 12 panecillos usa 100 g de azúcar, 50 g de mantequilla, 0,5 L de leche y 400 g de harina. Si se dispone de 500 g de azúcar, 200 g de mantequilla, 4 L de leche y 5 kg de harina, ¿cuántos panecillos como máximo se pueden hacer?",
        "correcta": "48",
        "distractores": ["60", "96", "120", "150"],
        "explicacion": "Tandas posibles: azúcar 5, mantequilla 4, leche 8, harina 12,5. La mantequilla limita: 4 tandas × 12 = 48 panecillos.",
        "dificultad": 2,
    },
    {
        "tema": "Ahorro de agua y volumen",
        "origen": "CMRJ 2018 - Q14",
        "enunciado": "Un baño de 15 minutos gasta 135 litros de agua. Si se reduce el baño a 9 minutos (uno por día), ¿cuánta agua se ahorra en 30 días?",
        "correcta": "1,62 m³",
        "distractores": ["2,43 m³", "162 dm³", "4,05 m³", "243.000 cm³"],
        "explicacion": "Consumo por minuto: 135 ÷ 15 = 9 L. Ahorro por baño: (15 − 9) × 9 = 54 L. En 30 días: 54 × 30 = 1.620 L = 1,62 m³.",
        "dificultad": 3,
    },
    {
        "tema": "Fracción del tiempo",
        "origen": "CMRJ 2018 - Q15",
        "enunciado": "Una persona pasa 10 h 24 min al día mirando el celular y duerme 8 horas. ¿Qué fracción de su tiempo despierto pasa en el celular?",
        "correcta": "13/20",
        "distractores": ["13/30", "11/20", "11/30", "2/3"],
        "explicacion": "Tiempo despierto: 24 − 8 = 16 h. 10 h 24 min = 10,4 h. 10,4 ÷ 16 = 0,65 = 13/20.",
        "dificultad": 3,
    },
    {
        "tema": "Mínimo común múltiplo (encuentro)",
        "origen": "CMRJ 2018 - Q16",
        "enunciado": "Dos ciclistas dan vueltas a una pista: una tarda 6 min 40 s por vuelta y la otra 8 min, a velocidad constante. Si salen juntas del mismo punto en sentidos contrarios, ¿en cuánto tiempo se reencontrarán por primera vez en el punto de partida?",
        "correcta": "40 minutos",
        "distractores": ["48 minutos", "32 minutos", "26 minutos y 40 segundos", "33 minutos y 20 segundos"],
        "explicacion": "6 min 40 s = 400 s y 8 min = 480 s. Se reencuentran en el punto de partida en el mcm(400, 480) = 2.400 s = 40 minutos.",
        "dificultad": 3,
    },
    {
        "tema": "Volumen y caudal",
        "origen": "CMRJ 2018 - Q17",
        "enunciado": "Una piscina en forma de bloque rectangular mide 10 m × 4 m × 1,5 m. Una bomba la llena a caudal constante: bombea 250 litros en 10 minutos. ¿Cuánto tiempo tarda en llenar el 25% de la piscina?",
        "correcta": "10 horas",
        "distractores": ["8 horas", "9 horas", "12 horas", "15 horas"],
        "explicacion": "Volumen = 10 × 4 × 1,5 = 60 m³ = 60.000 L. Caudal = 250 ÷ 10 = 25 L/min. 25% = 15.000 L. Tiempo = 15.000 ÷ 25 = 600 min = 10 horas.",
        "dificultad": 3,
    },
    {
        "tema": "Restos y periodicidad",
        "origen": "CMRJ 2018 - Q19",
        "enunciado": "Tres tiradores disparan a la vez. El primero acierta por primera vez en su 2º disparo y luego repite el patrón '3 fallos y 1 acierto'. El segundo acierta primero en su 3º disparo y luego '5 fallos y 1 acierto'. El tercero acierta primero en su 4º disparo y luego '7 fallos y 1 acierto'. Si cada uno hace 420 disparos, ¿cuántas veces aciertan los tres en el mismo número de disparo?",
        "correcta": "0",
        "distractores": ["4", "3", "2", "1"],
        "explicacion": "El primero acierta en 2, 6, 10, … (resto 2 al dividir por 4). El tercero en 4, 12, 20, … (resto 0 al dividir por 4). Como uno exige resto 2 y el otro resto 0 al dividir por 4, nunca coinciden: 0 veces.",
        "dificultad": 3,
    },
    {
        "tema": "Multiplicación y suma (ahorro)",
        "origen": "CMRJ 2018 - Q20",
        "enunciado": "El salario mínimo fue de R$ 788 en 2015, R$ 880 en 2016, R$ 937 en 2017 y R$ 954 en 2018. Una persona ahorró 1 salario mínimo en 2015, 2 en 2016, 3 en 2017 y 1 en 2018. ¿Cuánto ahorró en total?",
        "correcta": "R$ 6.313,00",
        "distractores": ["R$ 6.297,00", "R$ 6.256,00", "R$ 6.221,00", "R$ 6.193,00"],
        "explicacion": "788×1 + 880×2 + 937×3 + 954×1 = 788 + 1.760 + 2.811 + 954 = R$ 6.313,00.",
        "dificultad": 2,
    },
]
